name: ZenexClans
version: 1.0.0
api-version: 1.21
main: com.zenex.clans.ZenexClans
author: ZenexPlugins
description: 🏰 Клановая система

softdepend:
  - PlaceholderAPI

commands:
  clan:
    description: Главная команда кланов
    usage: /clan <create|disband|invite|accept|deny|list|info|kick|addbw|removebw|help>
    aliases: [c]

permissions:
  zenexclans.admin:
    default: op
  zenexclans.use:
    default: true
  zenexclans.leader:
    default: false
  zenexclans.coleader:
    default: false
